# Matches inputs: "managing_director" or "md"
managing_director = "SuperSecureMD99!"

# Matches inputs: "hr_admin", "hr", or "admin"
hr_admin = "AdminOpsManage2026!"

# Matches inputs: "ciso"
ciso = "SecuredNetworkShield82*"

# Matches inputs: "general_user" or "general"
general_user = "WelcomeStaffTeam1!"
