# Matches inputs: "managing_director" or "md"
managing_director = "SecureMD99!"

# Matches inputs: "hr_admin", "hr", or "admin"
hr_admin = "Adminmanage2026!"

# Matches inputs: "ciso"
ciso = "SecuredShield82*"

# Matches inputs: "general_user" or "general"
general_user = "StaffTeam1!"
